apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-manager-frontend
  labels:
    app: task-manager-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-manager-frontend
  template:
    metadata:
      labels:
        app: task-manager-frontend
    spec:
      containers:
        - name: nginx
          image: task-manager-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
