apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: {{ include "task-manager.fullname" . }}-postgres-pvc
  namespace: {{ .Release.Namespace }}

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: {{ .Values.postgres.storage }}
